export const FETCH_EPIC_WORK_TYPES_REQUEST = 'FETCH_EPIC_WORK_TYPES_REQUEST';
export const FETCH_EPIC_WORK_TYPES_SUCCESS = 'FETCH_EPIC_WORK_TYPES_SUCCESS';
export const FETCH_EPIC_WORK_TYPES_FAILURE = 'FETCH_EPIC_WORK_TYPES_FAILURE';
export const FETCH_EPIC_WORK_TYPE_BY_ID_REQUEST = 'FETCH_EPIC_WORK_TYPE_BY_ID_REQUEST';
export const FETCH_EPIC_WORK_TYPE_BY_ID_SUCCESS = 'FETCH_EPIC_WORK_TYPE_BY_ID_SUCCESS';
export const FETCH_EPIC_WORK_TYPE_BY_ID_FAILURE = 'FETCH_EPIC_WORK_TYPE_BY_ID_FAILURE';

export const CREATE_EPIC_WORK_TYPE_REQUEST = 'CREATE_EPIC_WORK_TYPE_REQUEST';
export const CREATE_EPIC_WORK_TYPE_SUCCESS = 'CREATE_EPIC_WORK_TYPE_SUCCESS';
export const CREATE_EPIC_WORK_TYPE_FAILURE = 'CREATE_EPIC_WORK_TYPE_FAILURE';

export const UPDATE_EPIC_WORK_TYPE_REQUEST = 'UPDATE_EPIC_WORK_TYPE_REQUEST';
export const UPDATE_EPIC_WORK_TYPE_SUCCESS = 'UPDATE_EPIC_WORK_TYPE_SUCCESS';
export const UPDATE_EPIC_WORK_TYPE_FAILURE = 'UPDATE_EPIC_WORK_TYPE_FAILURE';

export const DELETE_EPIC_WORK_TYPE_REQUEST = 'DELETE_EPIC_WORK_TYPE_REQUEST';
export const DELETE_EPIC_WORK_TYPE_SUCCESS = 'DELETE_EPIC_WORK_TYPE_SUCCESS';
export const DELETE_EPIC_WORK_TYPE_FAILURE = 'DELETE_EPIC_WORK_TYPE_FAILURE';

export const SELECT_EPIC_WORK_TYPE = 'SELECT_EPIC_WORK_TYPE';
export const DESELECT_EPIC_WORK_TYPE = 'DESELECT_EPIC_WORK_TYPE';
