// src/store/reducers/epicWorks/epicWorksTypes.js
export const FETCH_EPIC_WORKS_REQUEST = 'FETCH_EPIC_WORKS_REQUEST';
export const FETCH_EPIC_WORKS_SUCCESS = 'FETCH_EPIC_WORKS_SUCCESS';
export const FETCH_EPIC_WORKS_FAILURE = 'FETCH_EPIC_WORKS_FAILURE';
export const FETCH_EPIC_WORK_BY_ID_REQUEST = 'FETCH_EPIC_WORK_BY_ID_REQUEST';
export const FETCH_EPIC_WORK_BY_ID_SUCCESS = 'FETCH_EPIC_WORK_BY_ID_SUCCESS';
export const FETCH_EPIC_WORK_BY_ID_FAILURE = 'FETCH_EPIC_WORK_BY_ID_FAILURE';

export const CREATE_EPIC_WORK_REQUEST = 'CREATE_EPIC_WORK_REQUEST';
export const CREATE_EPIC_WORK_SUCCESS = 'CREATE_EPIC_WORK_SUCCESS';
export const CREATE_EPIC_WORK_FAILURE = 'CREATE_EPIC_WORK_FAILURE';

export const UPDATE_EPIC_WORK_REQUEST = 'UPDATE_EPIC_WORK_REQUEST';
export const UPDATE_EPIC_WORK_SUCCESS = 'UPDATE_EPIC_WORK_SUCCESS';
export const UPDATE_EPIC_WORK_FAILURE = 'UPDATE_EPIC_WORK_FAILURE';

export const DELETE_EPIC_WORK_REQUEST = 'DELETE_EPIC_WORK_REQUEST';
export const DELETE_EPIC_WORK_SUCCESS = 'DELETE_EPIC_WORK_SUCCESS';
export const DELETE_EPIC_WORK_FAILURE = 'DELETE_EPIC_WORK_FAILURE';

export const SELECT_EPIC_WORK = 'SELECT_EPIC_WORK';
export const DESELECT_EPIC_WORK = 'DESELECT_EPIC_WORK';
